name: Package Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate protos
        run: npx buf generate

      - name: Compile
        run: pnpm run compile

      - name: Install vsce
        run: pnpm add -g @vscode/vsce

      - name: Package extension
        run: pnpm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windsurf-api-vsix
          path: '*.vsix'

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
